version: '3'
services:
  devserver2:
    build: .
    domainname: dev.localhost.com
    ports: ['80:80']
    tty: true
    command: service nginx start ; npm run start

  testserver:
    build: .
    domainname: test.localhost.com
    command: service nginx restart ; npm start:testing ; npm lint && npm test
    expose: ["80"]

  prodserver:
    build: .
    domainname: prod.localhost.com
    command: service nginx restart ; npm start:production
    expose: ["80"]